url: http://zhued.github.io
baseurl: 

# Site settings
title: Edward Zhu
email: edward.r.zhu@gmail.com
description: "I like pandas"
resume-link: https://drive.google.com/file/d/0B8mMgx7E3Dn9OEZtYng1Nmc4RDQ/view

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 0099FF
  secondary: 33CCFF  
  secondary-dark: 333
  navbar: 0099FF
  navbar-sec: FFFFFF

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin 
    url: https://www.linkedin.com/profile/view?id=306788079
  - title: github
    url: http://github.com/zhued

# Postal address (add as many lines as necessary)
address:
  - line: 2624 Shavano Court
  - line: Fort Collins, CO

# Portfolio 
portfolio:
  - project: EZList
    modal: EZList
    intro: Prototype of an App
    tools: JustInMind
    icon: mobile
    url: https://github.com/zhued/EZList
    description: Developed for showing the wordcount of a Markdown flavored presentation or paper. asfasdfasdf

  - project: MDWordcount
    modal: MDWordcount
    intro: Wordcount for Markdown text files
    tools: PHP
    icon: toggle-down
    url: https://github.com/zhued/MDwordcounter
    description: Developed for showing the wordcount of a Markdown GitHub flavored presentation or paper. Written for CSCI 3155 - Principles of Programming Languages at CU Boulder.

  - project: Personal Website
    modal: Personal_Website
    intro: You are looking at it right now! 
    tools: Jekyll and Bootstrap
    icon: desktop
    url: https://github.com/zhued/zhued.github.io
    description: Developed for showing the wordcount of a Markdown flavored presentation or paper.

# Build settings
markdown: kramdown
permalink: pretty