# source:      _source
# destination: _deploy

# Site settings
title: Edward Zhu
email: edward.r.zhu@gmail.com
description: ""
baseurl: ""
url: "zhued.github.io"
github_username:  zhued

# Build settings
markdown: kramdown
permalink: pretty