url: https://zhued.github.io
baseurl: 

# Site settings
title: Edward Zhu
email: edward.r.zhu@gmail.com
description: "I like pandas"

# Color settings (hex-codes without the leading hash-tag)
# color:
#   primary: fed136
#   secondary: fec503  
#   secondary-dark: 333

color:
  primary: 0099FF
  secondary: 33CCFF  
  secondary-dark: 333
  navbar: 0099FF
  navbar-sec: FFFFFF

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin 
    url: https://www.linkedin.com/profile/view?id=306788079
  - title: github
    url: http://github.com/zhued
  # - title: email
  #   url: edward.r.zhu@gmail.com

# Postal address (add as many lines as necessary)
address:
  - line: 2624 Shavano Court
  - line: Fort Collins, CO

# Build settings
markdown: kramdown
permalink: pretty